---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- examples/
- gemfiles/
- spec/
- test/
